# Generated by Django 4.2.7 on 2023-12-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("文學", "文學"),
                    ("兒童", "兒童"),
                    ("哲學", "哲學"),
                    ("英語", "英語"),
                    ("金融", "金融"),
                    ("程式", "程式"),
                    ("其他", "其他"),
                ],
                default="文學",
                max_length=2,
                verbose_name="類型",
            ),
        ),
    ]
