# Generated by Django 4.2.7 on 2023-12-28 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="出版日期"
            ),
        ),
        migrations.AlterField(
            model_name="borrowingrecord",
            name="borrow_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="借閱日期"
            ),
        ),
    ]
