# Generated by Django 4.2.7 on 2024-01-01 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_book_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="admission_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="入館日期"
            ),
        ),
    ]
