# Generated by Django 4.2.7 on 2024-01-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_book_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="進貨價格"
            ),
        ),
    ]
