# Generated by Django 4.2.7 on 2024-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_reserverecord_reserve_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowingrecord",
            name="is_return",
            field=models.BooleanField(blank=True, default=False, verbose_name="是否歸還"),
        ),
    ]
